#!/bin/bash

course_file="/home/shuern/Downloads/course.txt"

#echo -e "\033[4m Search Course Details Form\033[0m"  # Underline
echo "  Search Course Details Form"
echo -e "\e[1;36m ---------------------------- \e[0m"
echo " "

# If the course code not found, will ask user whether want to continue input or not

nullInput=t
while [ $nullInput = "t" ]
do 
  echo -n " Enter Course Code: " ; read courseCode
  echo -e "\e[1;34m _____________________________________________________________________ \e[0m"
  echo " "
  
  if [ -z $courseCode ]
  then 
     echo -e "\033[31;5m Must enter a Course Code ! \033[0m"
     echo " "
     nullInput=t
  else  
     nullInput=f
  fi
done
  
 
courseCode=$(echo $courseCode | tr -s "" | tr "[[:lower:]]" "[[:upper:]]" )



# Save the grep result in the variable
  result="$(echo $courseCode | grep -w "$courseCode" "$course_file")" 

  while IFS=: read -r code name hours 
   do
    if [[ -n $code && -n $name && -n $hours ]] 
     then
     
       printf '%-17s%-3s%-17s\n' " Course Name " ":" "$name"
       printf '%-17s%-3s%-17s\n' " Credit Hours " ":" "$hours"
       
       echo " "
    else 
      
      echo -e " Course code: \e[1;33m $courseCode \e[0m does not exist !"
      
    fi
  done <<< $result

#-----------------------------------------------------
echo " "

validRespond=f
while [ $validRespond = "f" ]
do 
 echo " Search Another Course? (y)es or (q)uit: "
 echo -n " Press(q) to return to College Management Menu. " ; read respond
 
 if [[ $respond =~ ^[Y|y|Q|q]$ ]]
 then validRespond=t
 else 
   echo -e "\033[31;5m Invalid Input ! \033[0m"
   echo " Please enter (y)es or (q)quit."
   validRespond=f
 fi
done

echo " "

case $respond in
[Yy]) ./searchCourse
      exit
      ;;
[Qq]) echo " Closing the Search Course Details Form..."
      sleep 1
      ./ManagementMenu
      ;;
esac
        


